### ISSUE TITLE
Ruby Владивосток #8, 21 марта 2020

### ISSUE THREAD

**Issue by dmshvetsov** [ruby-vladivostok/meetup#8]
21 марта 2020, 19:00, Бар Holy-Hop, общение, напитки, еда и хорошее настроение.

[карта](https://2gis.ru/vladivostok/search/%D0%B2%D0%BB%D0%B0%D0%B4%D0%B8%D0%B2%D0%BE%D1%81%D1%82%D0%BE%D0%BA%2C%20%D1%85%D0%BE%D0%BB%D0%B8%D1%85%D0%BE%D0%BF/firm/70000001026993649/131.885775%2C43.117095?m=131.8858%2C43.117107%2F15.88) 

---

Ruby Vladivostok meetup, March 21, 2020

place HollyHop

**Comment by cyr-kov** [comment]
иии. Корово Вииирууус!

**Comment by forsaken1** [comment]
можно закрывать)

**Comment by dmshvetsov** [comment]
@forsaken1 верно! А есть фото в соц. сетях с митапа?

**Comment by forsaken1** [comment]
@iamdidev да я в телегу скидывал вроде
